In [36]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [60]:
def gradient_descent(x,y):
    m_cur=0
    b_cur=0
    iterations=1000000
    learning_rate=0.0001
    n=len(x)
    threshold=1e-6
    for i in range(iterations):
        y_predict=m_cur*x+b_cur
        m_deri=-(2/n)*sum(x*((y-y_predict)))
        b_deri=-(2/n)*sum((y-y_predict))
        if np.isnan(m_deri) or np.isinf(m_deri) or np.isnan(b_deri) or np.isinf(b_deri):
            print("Numerical instability encountered. Check data or learning rate.")
            break
        m_new=m_cur-learning_rate*m_deri
        b_new= b_cur-learning_rate*b_deri
        if(abs(m_new-m_cur)<threshold and abs(b_new-b_cur)<threshold):
            print("Convergence in:",i+1)
            print("m:",m_cur," b:",b_cur)
            return
        b_cur=b_new
        m_cur=m_new
    print("m:",m_cur," b:",b_cur)       
         
    
        

In [21]:
df=pd.read_csv("test_scores.csv")
df

name  math  cs
0   david    92  98
1   laura    56  68
2  sanjay    88  81
3     wei    70  80
4    jeff    80  83
5   aamir    49  52
6  venkat    65  66
7   virat    35  30
8  arthur    66  68
9    paul    67  73

In [28]:
x=np.array(df.iloc[0:,1],dtype=float)
y=np.array(df.iloc[0:,-1],dtype=float)
x,y

(array([92., 56., 88., 70., 80., 49., 65., 35., 66., 67.]),
 array([98., 68., 81., 80., 83., 52., 66., 30., 68., 73.]))

In [61]:
gradient_descent(x,y)

Convergence in: 268546
m: 1.0189655175003687  b: 1.8281034537010938


In [50]:
reg=linear_model.LinearRegression()
reg.fit(df[["math"]],df["cs"])
reg.coef_,reg.intercept_

(array([1.01773624]), np.float64(1.9152193111568891))