In [41]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.datasets import load_wine

In [22]:
wine=load_wine()
X=pd.DataFrame(wine.data,columns=wine.feature_names)
Y=wine.target

In [23]:
X.isnull().sum()

alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
dtype: int64

In [35]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [36]:
GNB=GaussianNB()

In [37]:
GNB.fit(X_train,Y_train)

GaussianNB()

In [38]:
GNB.predict(X_test)

array([0, 1, 1, 0, 2, 1, 2, 1, 0, 0, 1, 2, 1, 0, 0, 1, 1, 0, 2, 0, 0, 1,
       1, 0, 1, 0, 2, 0, 0, 2, 1, 1, 1, 2, 0, 0])

In [39]:
GNB.predict_proba(X_test)

array([[9.95851193e-01, 4.14880727e-03, 1.09116289e-24],
       [1.57612695e-18, 1.00000000e+00, 1.22965569e-28],
       [5.70452322e-14, 1.00000000e+00, 1.42792262e-10],
       [9.99999991e-01, 8.80119085e-09, 1.21969285e-27],
       [3.38566977e-29, 1.80318958e-14, 1.00000000e+00],
       [4.04474742e-04, 9.99595525e-01, 5.64380758e-17],
       [7.55573678e-26, 3.28509307e-12, 1.00000000e+00],
       [2.99997063e-07, 9.99999700e-01, 4.98339322e-19],
       [9.99999997e-01, 3.34984242e-09, 9.84513776e-33],
       [9.99999858e-01, 1.41724144e-07, 5.48943593e-25],
       [4.41567979e-06, 9.99995584e-01, 1.95604490e-20],
       [2.56030519e-21, 2.96942026e-06, 9.99997031e-01],
       [3.29049650e-11, 9.99999999e-01, 5.25418938e-10],
       [9.99999994e-01, 6.22489307e-09, 2.25845108e-33],
       [9.99826831e-01, 1.73169067e-04, 2.08212541e-21],
       [8.18012366e-12, 1.00000000e+00, 1.22692663e-19],
       [1.11079945e-08, 9.99999989e-01, 1.48911677e-13],
       [1.00000000e+00, 6.24534

In [40]:
GNB.score(X_test,Y_test)

0.9722222222222222

In [42]:
MNB=MultinomialNB()

In [43]:
MNB.fit(X_train,Y_train)

MultinomialNB()

In [44]:
MNB.predict(X_test)

array([0, 1, 1, 0, 2, 0, 2, 2, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 2, 0, 0, 1,
       2, 0, 1, 0, 2, 0, 0, 2, 1, 1, 2, 2, 0, 0])

In [45]:
MNB.predict_proba(X_test)

array([[9.99762800e-01, 9.75374859e-06, 2.27446058e-04],
       [1.89441387e-14, 9.99610714e-01, 3.89286330e-04],
       [1.18275437e-13, 9.88220640e-01, 1.17793600e-02],
       [1.00000000e+00, 3.95356962e-25, 6.04401995e-19],
       [2.52425358e-05, 1.48611809e-04, 9.99826146e-01],
       [9.99973088e-01, 5.00255510e-07, 2.64115524e-05],
       [3.36229455e-07, 1.24159858e-03, 9.98758065e-01],
       [1.67918440e-01, 2.07518425e-01, 6.24563135e-01],
       [1.00000000e+00, 2.09196337e-21, 6.52349844e-16],
       [1.00000000e+00, 1.68766950e-16, 2.64716198e-12],
       [4.20391707e-06, 9.20470692e-01, 7.95251041e-02],
       [5.37366520e-01, 2.02102974e-04, 4.62431377e-01],
       [1.65382889e-06, 8.90264057e-01, 1.09734290e-01],
       [1.00000000e+00, 2.45780643e-24, 3.63924415e-18],
       [9.99999995e-01, 4.18113620e-12, 4.80528640e-09],
       [1.73496888e-12, 9.90847038e-01, 9.15296201e-03],
       [4.13862817e-23, 9.99987912e-01, 1.20883745e-05],
       [1.00000000e+00, 1.30305

In [46]:
MNB.score(X_test,Y_test)

0.8333333333333334