In [1]:
import numpy as np

In [2]:
data=np.random.rand(2,3,4)

In [3]:
zeroes=np.zeros((2,2,2))

In [4]:
data

array([[[0.64370493, 0.94756078, 0.03784921, 0.71581812],
        [0.50517607, 0.93206524, 0.03337005, 0.33375243],
        [0.0633121 , 0.95947011, 0.74226304, 0.28834839]],

       [[0.2438218 , 0.11104074, 0.36524898, 0.43650347],
        [0.3028956 , 0.2874226 , 0.02362202, 0.92327857],
        [0.73952335, 0.74081807, 0.70476155, 0.78862761]]])

In [5]:
full=np.full((2,2,2),7)

In [6]:
ones=np.ones((2,2,2))

In [8]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [9]:
arr=np.array([[1,2,3],[1,2,3]])

In [10]:
type(arr)

numpy.ndarray

In [11]:
shape=data.shape

In [12]:
size=data.size
types=data.dtype

In [13]:
size


24

In [14]:
types

dtype('float64')

In [19]:
arr=data[0]
slicer=data[0][0:2]
reverse=data[-1]
singleval=data[0][0][0]

In [20]:
data

array([[[0.64370493, 0.94756078, 0.03784921, 0.71581812],
        [0.50517607, 0.93206524, 0.03337005, 0.33375243],
        [0.0633121 , 0.95947011, 0.74226304, 0.28834839]],

       [[0.2438218 , 0.11104074, 0.36524898, 0.43650347],
        [0.3028956 , 0.2874226 , 0.02362202, 0.92327857],
        [0.73952335, 0.74081807, 0.70476155, 0.78862761]]])

In [21]:
arr,slicer

(array([[0.64370493, 0.94756078, 0.03784921, 0.71581812],
        [0.50517607, 0.93206524, 0.03337005, 0.33375243],
        [0.0633121 , 0.95947011, 0.74226304, 0.28834839]]),
 array([[0.64370493, 0.94756078, 0.03784921, 0.71581812],
        [0.50517607, 0.93206524, 0.03337005, 0.33375243]]))

In [18]:
reverse

array([[0.2438218 , 0.11104074, 0.36524898, 0.43650347],
       [0.3028956 , 0.2874226 , 0.02362202, 0.92327857],
       [0.73952335, 0.74081807, 0.70476155, 0.78862761]])

In [22]:
singleval

np.float64(0.6437049322284336)

In [23]:
list1=np.random.rand(10)
list2=np.random.rand(10)

In [25]:
list2

array([0.55286878, 0.38855532, 0.3567932 , 0.00607131, 0.46292111,
       0.12533803, 0.8101459 , 0.75808085, 0.21220697, 0.14903943])

In [26]:
add=np.add(list1,list2)
sub=np.subtract(list1,list2)
div=np.divide(list1,list2)
mult=np.multiply(list1,list2)
dot=np.dot(list1,list2)

In [28]:
list1

array([0.49785902, 0.26550569, 0.9888139 , 0.1725759 , 0.20274294,
       0.66829718, 0.79132511, 0.48189172, 0.82857113, 0.42521346])

In [29]:
list2

array([0.55286878, 0.38855532, 0.3567932 , 0.00607131, 0.46292111,
       0.12533803, 0.8101459 , 0.75808085, 0.21220697, 0.14903943])

In [34]:
dot

np.float64(2.15548505834677)

**Remember saplemm for function.**

In [36]:
data


array([[[0.64370493, 0.94756078, 0.03784921, 0.71581812],
        [0.50517607, 0.93206524, 0.03337005, 0.33375243],
        [0.0633121 , 0.95947011, 0.74226304, 0.28834839]],

       [[0.2438218 , 0.11104074, 0.36524898, 0.43650347],
        [0.3028956 , 0.2874226 , 0.02362202, 0.92327857],
        [0.73952335, 0.74081807, 0.70476155, 0.78862761]]])

In [37]:
data[0][0][0]=700

In [38]:
data

array([[[7.00000000e+02, 9.47560777e-01, 3.78492143e-02, 7.15818122e-01],
        [5.05176070e-01, 9.32065236e-01, 3.33700465e-02, 3.33752432e-01],
        [6.33120991e-02, 9.59470111e-01, 7.42263035e-01, 2.88348394e-01]],

       [[2.43821797e-01, 1.11040743e-01, 3.65248978e-01, 4.36503467e-01],
        [3.02895604e-01, 2.87422596e-01, 2.36220197e-02, 9.23278567e-01],
        [7.39523347e-01, 7.40818075e-01, 7.04761547e-01, 7.88627611e-01]]])

In [39]:
data.sort()
data

array([[[3.78492143e-02, 7.15818122e-01, 9.47560777e-01, 7.00000000e+02],
        [3.33700465e-02, 3.33752432e-01, 5.05176070e-01, 9.32065236e-01],
        [6.33120991e-02, 2.88348394e-01, 7.42263035e-01, 9.59470111e-01]],

       [[1.11040743e-01, 2.43821797e-01, 3.65248978e-01, 4.36503467e-01],
        [2.36220197e-02, 2.87422596e-01, 3.02895604e-01, 9.23278567e-01],
        [7.04761547e-01, 7.39523347e-01, 7.40818075e-01, 7.88627611e-01]]])

In [43]:
data=data.reshape(2,2,-1)

In [44]:
data

array([[[3.78492143e-02, 7.15818122e-01, 9.47560777e-01, 7.00000000e+02,
         3.33700465e-02, 3.33752432e-01],
        [5.05176070e-01, 9.32065236e-01, 6.33120991e-02, 2.88348394e-01,
         7.42263035e-01, 9.59470111e-01]],

       [[1.11040743e-01, 2.43821797e-01, 3.65248978e-01, 4.36503467e-01,
         2.36220197e-02, 2.87422596e-01],
        [3.02895604e-01, 9.23278567e-01, 7.04761547e-01, 7.39523347e-01,
         7.40818075e-01, 7.88627611e-01]]])

In [52]:
list1=np.append(list1,6)
list1=np.insert(list1,4,12)
list1

array([ 0.49785902,  0.26550569,  0.9888139 ,  0.1725759 , 12.        ,
        0.20274294,  0.66829718,  0.79132511,  0.48189172,  0.82857113,
        0.42521346,  6.        ,  7.        ,  4.        ,  4.        ,
        6.        ,  7.        ,  6.        ,  6.        ,  6.        ,
        6.        ,  6.        ])

In [53]:
data

array([[[3.78492143e-02, 7.15818122e-01, 9.47560777e-01, 7.00000000e+02,
         3.33700465e-02, 3.33752432e-01],
        [5.05176070e-01, 9.32065236e-01, 6.33120991e-02, 2.88348394e-01,
         7.42263035e-01, 9.59470111e-01]],

       [[1.11040743e-01, 2.43821797e-01, 3.65248978e-01, 4.36503467e-01,
         2.36220197e-02, 2.87422596e-01],
        [3.02895604e-01, 9.23278567e-01, 7.04761547e-01, 7.39523347e-01,
         7.40818075e-01, 7.88627611e-01]]])

In [54]:
np.delete(data,0,axis=1)

array([[[0.50517607, 0.93206524, 0.0633121 , 0.28834839, 0.74226304,
         0.95947011]],

       [[0.3028956 , 0.92327857, 0.70476155, 0.73952335, 0.74081807,
         0.78862761]]])