In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge

In [61]:
df=pd.read_csv("HousingDataset.csv")

In [62]:
df.head()

Suburb             Address  Rooms Type      Price Method SellerG  \
0  Abbotsford       68 Studley St      2    h        NaN     SS  Jellis   
1  Abbotsford        85 Turner St      2    h  1480000.0      S  Biggin   
2  Abbotsford     25 Bloomburg St      2    h  1035000.0      S  Biggin   
3  Abbotsford  18/659 Victoria St      3    u        NaN     VB  Rounds   
4  Abbotsford        5 Charles St      3    h  1465000.0     SP  Biggin   

        Date  Distance  Postcode  ...  Bathroom  Car  Landsize  BuildingArea  \
0  3/09/2016       2.5    3067.0  ...       1.0  1.0     126.0           NaN   
1  3/12/2016       2.5    3067.0  ...       1.0  1.0     202.0           NaN   
2  4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0          79.0   
3  4/02/2016       2.5    3067.0  ...       2.0  1.0       0.0           NaN   
4  4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0         150.0   

   YearBuilt         CouncilArea Lattitude  Longtitude             Regionname  \
0        NaN  Yarra City Council  -37.8014    144.9958  Northern Metropolitan   
1        NaN  Yarra City Council  -37.7996    144.9984  Northern Metropolitan   
2     1900.0  Yarra City Council  -37.8079    144.9934  Northern Metropolitan   
3        NaN  Yarra City Council  -37.8114    145.0116  Northern Metropolitan   
4     1900.0  Yarra City Council  -37.8093    144.9944  Northern Metropolitan   

  Propertycount  
0        4019.0  
1        4019.0  
2        4019.0  
3        4019.0  
4        4019.0  

[5 rows x 21 columns]

In [63]:
df.head()

Suburb             Address  Rooms Type      Price Method SellerG  \
0  Abbotsford       68 Studley St      2    h        NaN     SS  Jellis   
1  Abbotsford        85 Turner St      2    h  1480000.0      S  Biggin   
2  Abbotsford     25 Bloomburg St      2    h  1035000.0      S  Biggin   
3  Abbotsford  18/659 Victoria St      3    u        NaN     VB  Rounds   
4  Abbotsford        5 Charles St      3    h  1465000.0     SP  Biggin   

        Date  Distance  Postcode  ...  Bathroom  Car  Landsize  BuildingArea  \
0  3/09/2016       2.5    3067.0  ...       1.0  1.0     126.0           NaN   
1  3/12/2016       2.5    3067.0  ...       1.0  1.0     202.0           NaN   
2  4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0          79.0   
3  4/02/2016       2.5    3067.0  ...       2.0  1.0       0.0           NaN   
4  4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0         150.0   

   YearBuilt         CouncilArea Lattitude  Longtitude             Regionname  \
0        NaN  Yarra City Council  -37.8014    144.9958  Northern Metropolitan   
1        NaN  Yarra City Council  -37.7996    144.9984  Northern Metropolitan   
2     1900.0  Yarra City Council  -37.8079    144.9934  Northern Metropolitan   
3        NaN  Yarra City Council  -37.8114    145.0116  Northern Metropolitan   
4     1900.0  Yarra City Council  -37.8093    144.9944  Northern Metropolitan   

  Propertycount  
0        4019.0  
1        4019.0  
2        4019.0  
3        4019.0  
4        4019.0  

[5 rows x 21 columns]

In [64]:

df.head()

Suburb             Address  Rooms Type      Price Method SellerG  \
0  Abbotsford       68 Studley St      2    h        NaN     SS  Jellis   
1  Abbotsford        85 Turner St      2    h  1480000.0      S  Biggin   
2  Abbotsford     25 Bloomburg St      2    h  1035000.0      S  Biggin   
3  Abbotsford  18/659 Victoria St      3    u        NaN     VB  Rounds   
4  Abbotsford        5 Charles St      3    h  1465000.0     SP  Biggin   

        Date  Distance  Postcode  ...  Bathroom  Car  Landsize  BuildingArea  \
0  3/09/2016       2.5    3067.0  ...       1.0  1.0     126.0           NaN   
1  3/12/2016       2.5    3067.0  ...       1.0  1.0     202.0           NaN   
2  4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0          79.0   
3  4/02/2016       2.5    3067.0  ...       2.0  1.0       0.0           NaN   
4  4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0         150.0   

   YearBuilt         CouncilArea Lattitude  Longtitude             Regionname  \
0        NaN  Yarra City Council  -37.8014    144.9958  Northern Metropolitan   
1        NaN  Yarra City Council  -37.7996    144.9984  Northern Metropolitan   
2     1900.0  Yarra City Council  -37.8079    144.9934  Northern Metropolitan   
3        NaN  Yarra City Council  -37.8114    145.0116  Northern Metropolitan   
4     1900.0  Yarra City Council  -37.8093    144.9944  Northern Metropolitan   

  Propertycount  
0        4019.0  
1        4019.0  
2        4019.0  
3        4019.0  
4        4019.0  

[5 rows x 21 columns]

In [65]:
df.isnull().sum()

Suburb               0
Address              0
Rooms                0
Type                 0
Price             7610
Method               0
SellerG              0
Date                 0
Distance             1
Postcode             1
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
YearBuilt        19306
CouncilArea          3
Lattitude         7976
Longtitude        7976
Regionname           3
Propertycount        3
dtype: int64

In [66]:
df=df.fillna({"Bedroom2":0,"Bathroom":0,"Car":0})
df["Landsize"]=df["Landsize"].fillna(df["Landsize"].mean())

In [67]:
df["Distance"]=df["Distance"].fillna(df["Distance"].mean())
df["YearBuilt"]=df["YearBuilt"].fillna(df["YearBuilt"].mean())
df["Lattitude"]=df["Lattitude"].fillna(df["Lattitude"].mean())
df["Longtitude"]=df["Longtitude"].fillna(df["Longtitude"].mean())
df["Propertycount"]=df["Propertycount"].fillna(df["Propertycount"].mean())

In [68]:
df.drop("Postcode",inplace=True,axis=1)

In [69]:
df.head()
df.drop(["Suburb","Address","Type","Method","SellerG","Date","BuildingArea","YearBuilt","CouncilArea","Regionname"],axis=1,inplace=True)

In [70]:
df.isnull().sum()

Rooms               0
Price            7610
Distance            0
Bedroom2            0
Bathroom            0
Car                 0
Landsize            0
Lattitude           0
Longtitude          0
Propertycount       0
dtype: int64

In [71]:
df.dropna(inplace=True)

In [88]:
X=df.drop("Price",axis=1)
Y=df.Price
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)
df

Rooms      Price  Distance  Bedroom2  Bathroom  Car    Landsize  \
1          2  1480000.0       2.5       2.0       1.0  1.0  202.000000   
2          2  1035000.0       2.5       2.0       1.0  0.0  156.000000   
4          3  1465000.0       2.5       3.0       2.0  0.0  134.000000   
5          3   850000.0       2.5       3.0       2.0  1.0   94.000000   
6          4  1600000.0       2.5       3.0       1.0  2.0  120.000000   
...      ...        ...       ...       ...       ...  ...         ...   
34852      4  1480000.0       6.3       4.0       1.0  3.0  593.000000   
34853      2   888000.0       6.3       2.0       2.0  1.0   98.000000   
34854      2   705000.0       6.3       2.0       1.0  2.0  220.000000   
34855      3  1140000.0       6.3       0.0       0.0  0.0  593.598993   
34856      2  1020000.0       6.3       2.0       1.0  0.0  250.000000   

       Lattitude  Longtitude  Propertycount  
1     -37.799600  144.998400         4019.0  
2     -37.807900  144.993400         4019.0  
4     -37.809300  144.994400         4019.0  
5     -37.796900  144.996900         4019.0  
6     -37.807200  144.994100         4019.0  
...          ...         ...            ...  
34852 -37.810530  144.884670         6543.0  
34853 -37.815510  144.888260         6543.0  
34854 -37.822860  144.878560         6543.0  
34855 -37.810634  145.001851         6543.0  
34856 -37.818100  144.893510         6543.0  

[27247 rows x 10 columns]

In [89]:
model1=LinearRegression()

In [90]:
model1.fit(X_train,Y_train)

LinearRegression()

In [91]:
model1.predict(X_test)

array([ 657178.68713191, 1828374.37175289,  986736.74645299, ...,
       1535429.7425034 , 1545331.89266738,  896253.15011936],
      shape=(5450,))

In [94]:
model1.score(X_test,Y_test)

0.44179646147974894

In [95]:
model1.score(X_train,Y_train)

0.4408202816475958

In [96]:
model2=Lasso()

In [97]:
model2.fit(X_train,Y_train)

Lasso()

In [98]:
model2.predict(X_test)

array([ 657194.30557391, 1828352.13359749,  986734.04689306, ...,
       1535418.24021921, 1545319.75611931,  896251.59475911],
      shape=(5450,))

In [86]:
model2.score(X_test,Y_test)

0.4063089507845581

In [99]:
model2.score(X_train,Y_train)

0.4408202811599191

In [100]:
model3=Ridge()

In [104]:
model3.fit(X_train,Y_train)

Ridge()

In [105]:
model3.predict(X_test)

array([ 658145.27733749, 1827176.80625337,  986703.73622486, ...,
       1535009.41117832, 1544924.50093731,  896272.49420673],
      shape=(5450,))

In [106]:
model3.score(X_test,Y_test)

0.4418038403165161